const { defineConfig } = require('@vue/cli-service');
const path = require('path');

/**
 * Get the updated HtmlWebpackPlugin configuration
 * @param {Object} [defaultConfig={}] - The default config object
 * @returns {Object} The updated HtmlWebpackPlugin config
 */
const getHtmlPluginConfig = (defaultConfig = {}) => {
    const { templateParameters: oldTemplateParams = {} } = defaultConfig || {};
    return {
        ...(defaultConfig || {}),
        templateParameters: {
            ...oldTemplateParams,
            lang: 'en',
        },
        template: path.resolve(__dirname, 'index.html'),
        favicon: path.resolve(__dirname, 'static', 'favicon.ico'),
        title: 'example app',
    };
};

/**
 * Whether the current environment is production
 * @type {boolean}
 * @description Determines whether the environment is production based on the NODE_ENV environment variable
 */
const isProduction = process.env?.NODE_ENV === 'production';

/**
 * Path to the newer babel-loader
 * @type {string}
 * @description Points to the babel-loader under the project root
 */
const newBabelLoader = path.resolve(__dirname, 'node_modules/babel-loader/lib/index.js');

module.exports = defineConfig(() => {
    return {
        transpileDependencies: isProduction,
        lintOnSave: 'error',
        devServer: {
            port: 2000,
            client: {
                overlay: {
                    warnings: false,
                },
            },
        },
        chainWebpack(config) {
            config
                .entry('app')
                .clear()
                .add(path.resolve(__dirname, 'src', 'main.tsx'))
                .end()
                // Make .ts & .tsx files use babel-loader (@babel/preset-typescript)
                .module.rule('ts')
                .test(/\.m?tsx?$/)
                .use('babel-loader')
                .loader(newBabelLoader)
                .options({
                    // Critical: explicitly point to the babel config in the project root
                    configFile: path.resolve(__dirname, 'babel.config.js'),
                })
                .end()
                .end()
                .end()
                .module.rule('js')
                .test(/\.m?jsx?$/)
                .use('babel-loader')
                .loader(newBabelLoader)
                .options({
                    // Critical: explicitly point to the babel config in the project root
                    configFile: path.resolve(__dirname, 'babel.config.js'),
                })
                .end()
                .end()
                .end()
                // Transpile the SFC wrapper code generated by vue-loader itself
                // (e.g. `const __exports__ = exportComponent(script, [['__scopeId', ...]])`).
                // Unlike <script> blocks, this code is NOT routed through the cloned
                // babel rules, so without this the production output keeps `const` even
                // with ES5 browserslist targets.
                // Implemented as a separate rule (instead of adding babel-loader to the
                // 'vue' rule) because the 'vue' rule must still apply to language-block
                // requests (style/template/script via ?vue query) where babel must not
                // run (e.g. SCSS is not JS). The resourceQuery { not: [/vue/] } keeps
                // this rule on the bare SFC request only. enforce: 'post' both keeps
                // VueLoaderPlugin from mistaking this rule for the vue rule (it skips
                // enforce rules) and orders post loaders after normal loaders, so the
                // chain becomes [babel-loader(post), vue-loader(normal)] and babel runs
                // on vue-loader's generated output.
                .when(isProduction, _config => {
                    _config.module
                        .rule('vue-main')
                        .post()
                        .test(/\.vue$/)
                        .resourceQuery({ not: [/vue/] })
                        .use('babel-loader')
                        .loader(newBabelLoader)
                        .options({
                            configFile: path.resolve(__dirname, 'babel.config.js'),
                        })
                        .end()
                        .end()
                        .end();
                })
                .resolve.extensions.merge(['.ts', '.tsx', '.js', '.jsx', '.vue', '.json'])
                .end()
                .alias.set('~', path.resolve(__dirname, 'src'))
                .set('assets', path.resolve(__dirname, 'src/assets'))
                .end()
                .end()
                .plugin('html')
                .tap(args => {
                    const [defaultConf, ...rest] = args;
                    return [getHtmlPluginConfig(defaultConf), ...rest].filter(Boolean);
                })
                .end();
        },
        css: {
            loaderOptions: {
                css: {
                    modules: {
                        auto(resourcePath) {
                            return resourcePath.includes('.module.');
                        },
                        // css-module hash
                        localIdentName: '[local]__[hash:base64]',
                        exportLocalsConvention(name) {
                            // home-view__text--red → homeView__text_red
                            const camel = name
                                .replace(/--/g, '_') // First replace -- with _
                                .replace(/-([a-z])/g, (_, char) => char.toUpperCase()); // Camel-case -
                            return [name, camel];
                        },
                    },
                },
            },
        },
    };
});
